[project]
name = "isaac"
version = "0.0.1"
description = "Simple ACP agent"
requires-python = ">=3.12"
dependencies = [
    "agent-client-protocol==0.6.3",
    "pydantic-ai==1.9.1",
]

[project.scripts]
isaac = "isaac.main:main_entry"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
test = [
    "ruff",
    "pytest",
    "pytest-asyncio",
]

[tool.ruff]
line-length = 100

[tool.hatch.build.targets.wheel]
packages = ["src/isaac"]
